modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "mpbruntimeextractor"
version = "0.1.0"
displayName = "MPB Runtime Extractor"
description = '''Minecraft Pack Builder runtime registry extractor.'''

[[dependencies."mpbruntimeextractor"]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."mpbruntimeextractor"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
