plugins {
    id 'base'
}

allprojects {
    group = providers.gradleProperty('mod_group').get()
    version = providers.gradleProperty('mod_version').get()

    tasks.withType(org.gradle.api.tasks.bundling.AbstractArchiveTask).configureEach {
        preserveFileTimestamps = false
        reproducibleFileOrder = true
    }
}
